# where I actively play with things

THEME_NAME = "test"

env.HOME = '/Users/nathan'

emacs.theme = "tarp-mcfay"

# BG_COMMAND="${HOME}/.fehbg"
# BG_COMMAND="hsetroot -solid '{{.color.focused.background}}'"
BG_COMMAND="wallmac tile '{{.env.HOME}}/Downloads/mpv-shot0095.jpg'"

font.mono.family = "Go Mono"
font.variable.family = "Equity Text B"

# mkb.complete = "â—†"
# mkb.sep = "â¬–"
# mkb.empty = "â—‡"

# st.prompt_char = 'ðŸ”µ'

mkb.complete = "â– "
mkb.sep = "â–©"
mkb.empty = "â–¡"

st.prompt_char='%'
bspwm.window-gap = 24
x.padding = 5

bspwm.monocle-window-percent = 0.55

font.mono.size = 18
font.variable.size = 18

picom.shadow.enabled = false

bspwm.bspwmrc-extend = """
tag_borders &
subscription_rules &
"""
