# where I actively play with things

THEME_NAME = "test"

emacs.theme = "tarp-mcfay"

# BG_COMMAND="${HOME}/.fehbg"
BG_COMMAND="hsetroot -solid '{{.color.focused.background}}'"

font.mono.family = "Go Mono"
font.variable.family = "Charter"

mkb.complete = "◆"
mkb.sep = "◆"
mkb.empty = "◇"

st.prompt_char='%'
bspwm.window.gap = 32
x.padding = 5

bspwm.monocle-window-percent = 0.55

font.mono.size = 12
font.variable.size = 12

picom.shadow.enabled = false


bspwm.bspwmrc-extend = """
tag_borders &
subscription_rules &
"""
